### ISSUE TITLE
Cannot get the Python 3.5 package to compile on XCode 8

### ISSUE THREAD

**Issue by ProfFan** [pybee/Python-Apple-support#12]
Hi,

I tried to compile the repo on XCode 8.1. The compile only fails for Python with the following message:
```bash
# Configure target Python
cp -f /Users/proffan/Projects/Development/ios/Python-Apple-support/patch/Python/Setup.embedded build/iOS/Python-3.5.2-iphonesimulator.x86_64/Modules/Setup.embedded
cd build/iOS/Python-3.5.2-iphonesimulator.x86_64 && PATH=/Users/proffan/Projects/Development/ios/Python-Apple-support/build/macOS/Python-3.5.2-macosx.x86_64/python/bin:/usr/local/sbin:/usr/local/bin:/Users/proffan/.rbenv/bin:/usr/bin:/bin:/usr/sbin:/sbin ./configure CC="xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk -miphoneos-version-min=7.0 " LD="xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk -miphoneos-version-min=7.0 " --host=x86_64-apple-iOS --build=x86_64-apple-darwin16.1.0 --prefix=/Users/proffan/Projects/Development/ios/Python-Apple-support/build/iOS/Python-3.5.2-iphonesimulator.x86_64/dist --without-pymalloc --without-doc-strings --disable-ipv6 --without-ensurepip ac_cv_file__dev_ptmx=no ac_cv_file__dev_ptc=no
checking build system type... x86_64-apple-darwin16.1.0
checking host system type... Invalid configuration `x86_64-apple-iOS': system `iOS' not recognized
configure: error: /bin/sh ./config.sub x86_64-apple-iOS failed
make: *** [build/iOS/Python-3.5.2-iphonesimulator.x86_64/Makefile] Error 1
```

I think the problem is with the `--host` option, but I have no idea how to change that line.

Thank you again for your great work.

**Comment by dalcacer** [comment]
Hello,
I stumbled over the exact same issue using XCode 8.2.1 and targeting iOS 10.2.

By setting `--host=aarch64-apple-ios` the build seemed to start, basically. It doesn't work though, due to a compile-time error regarding `Python\random.c` ...

**Comment by freakboy3742** [comment]
Thanks for the report.

Based on the error you're seeing, it looks like a patch hasn't been applied correctly - the iOS target has to be added to one of the configure scripts, as it's isn't supported natively by automake. I'll have to take a closer look next time I do a release.

**Comment by dalcacer** [comment]
Hello,
first of all thanks for your great work and your reply.

After some hours of fiddling around, I've got a little follow up to that issue. The build seems to work (for all targets/platforms) with some minor changes to the [pybee 3.5 branch](https://github.com/pybee/Python-Apple-support/tree/3.5).

As mentioned above the `configure --host flag` needs to be altered. It seems like this is necessary due to capitalisation issue.
Instead of fixing the value to `-ios` (as suggested before) a call to tr should solve this problem in a more robust way for all targets (sadly, a GNU Make call to lc didn’t work out…):

* `$$(MACHINE_DETAILED-$1)-apple-$2` to `--host=$$(MACHINE_DETAILED-$1)-apple-$(shell echo $2 | tr '[A-Z]' ‚[a-z]‘)`

Addressing the upcoming compilation errors. They've been discussed in the accompanying [python.org issue23670](http://b
ugs.python.org/issue23670) earlier this year.

For now, removing the affected lines from the source seems to work. However, this doesn't seem to be a no long-term solution, and might eventually result in runtime problems.

* `sed -ie 's/getentropy(buffer, len);/res=0;/' $$(PYTHON_DIR-$1)/Python/random.c`
* `sed -ie 's/ret = clock_settime((clockid_t)clk_id, &tp);/ret=0;/' $$(PYTHON_DIR-$1)/Modules/timemodule.c` 

Kind Regards

**Comment by freakboy3742** [comment]
Thanks for those updates. I'll take a look at getting those changes integrated as soon as I get a chance.

**Comment by kersson** [comment]
I think a better approach is to patch the `pyconfig.h` (https://github.com/ButterflyNetwork/Python-Apple-support/commit/21ec86a5413ba453775e4c690e6ac20451f20ab8):
```make
sed -ie 's|\#define HAVE_GETENTROPY 1|/* \#undef HAVE_GETENTROPY */|' $$(PYTHON_DIR-$1)/pyconfig.h
sed -ie 's|\#define HAVE_CLOCK_GETTIME 1|/* \#undef HAVE_CLOCK_GETTIME */|' $$(PYTHON_DIR-$1)/pyconfig.h
```
Or even better yet, figure out how to get `autoconf` to properly detect these properties for iOS.

**Comment by freakboy3742** [comment]
This should be addressed in the most recent binary builds (uploading as I type)
