### ISSUE TITLE
The Problem with Xcode Swift IOS

### ISSUE THREAD

**Issue by aboutsajjad** [pybee/Python-Apple-support#21]
Hi 
first of all thanks for your grate work.
I am trying to embed python into swift IOS but when ever i try to call the function `Py_Initialize()` i get the error 
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

Current thread 0x00000001083c83c0 (most recent call first):
(lldb) 
```
Version using: Python-3.5-iOS-support.b3 and tried 3.4
I imported `libz.tbd` and `libsqlite.tbd` and what should i set  `PYTHONHOME` from environment variables?
Thanks a lot.

**Comment by freakboy3742** [comment]
The best guide I can give you is to look at the [mainline for the iOS template project](https://github.com/pybee/Python-iOS-template/blob/3.5/%7B%7B%20cookiecutter.dir_name%20%7D%7D/%7B%7B%20cookiecutter.app_name%20%7D%7D/main.m) - that should show you what needs to be set up in order to get Py_Initialize and the other parts of the Python runtime working.
