### ISSUE TITLE
Unable to submit app which contains the Python.framework

### ISSUE THREAD

**Issue by gm6379** [pybee/Python-Apple-support#26]
I tried to submit an app to iTunes connect which contains your Python.framework and I get this error:

> Dear developer,
>
> We have discovered one or more issues with your recent delivery for "Reroo – find cheap last minute train tickets". To process your delivery, the following issues must be corrected:
> 
> This bundle is invalid - The Info.plist file for /Payload/Reroo.app/Library/Python.framework is missing or could not be read.
> 
> Invalid Bundle - The bundle at '/Payload/Reroo.app/Library/Python.framework' does not contain a bundle executable.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.

**Comment by freakboy3742** [comment]
@gm6379 Thanks for the report. I haven't see this complaint from the app store before; however, it shouldn't be too hard to correct.

**Comment by milos1290** [comment]
Just rename Python.framework to something else. I.E Python. They are scanning .framework containers for metadata.

**Comment by gm6379** [comment]
I removed the extension altogether which made it a folder instead of a framework and that seemed to fix the error, thanks!

**Comment by Siege097** [comment]
I am getting the same error but am a little confused on how to resolve it. When I try to change the name of the python.framework file I get an error that the python/python.h file can not be found.

also I have been using the framework as a linked framework.  In reading up on the above error people are suggesting that I should embed the framework instead of linking it when I submit the app to iTunes connect, but when I do this I'm getting a code signing error that says there is a problem with the python.framework.  I have been hunting around for a solution to that problem, but I am not even sure that embedding will resolve the issue.  Any insights you have on how to structure the build for iTunes Connect would be greatly appreciated.  Thanks

**Comment by freakboy3742** [comment]
If you use a recent version of the Python support libraries, this is exactly what is done. If you're still seeing .framework folders, you're somehow getting a stale version of the Python support library.

**Comment by Siege097** [comment]
OK thanks, yes i'll update the python libraries.  Thanks for your help!
