### ISSUE TITLE
sys/random.h not found in when compiling 2.7.13

### ISSUE THREAD

**Issue by frmdstryr** [pybee/Python-Apple-support#27]
```
Python/random.c:7:10: fatal error: 'sys/random.h' file not found
#include <sys/random.h>
         ^
```
Keep getting this error. Seems to be related to this ticket. https://bugs.python.org/issue29057

Commenting the include statement out seems to work.

And on some platforms appletvos.arm64, watchos.arm7k.  I'm getting:

```
Python/random.c:117:19: error: implicit declaration of function 'getentropy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            res = getentropy(buffer, len);
                  ^
```

**Comment by cfagot** [comment]
I get a similar error, but it's a link error.  From the python bug linked above it seems to depend on OS X and Xcode version.  I'm using OS X 10.11.6 and Xcode 8.2.1.  Build and config 
[build_out.log](https://github.com/pybee/Python-Apple-support/files/1479665/build_out.log)
[config.log](https://github.com/pybee/Python-Apple-support/files/1479666/config.log)

logs are attached but punchline is:

dyld: lazy symbol binding failed: Symbol not found: _getentropy
  Referenced from: /Users/me/dev/Python-Apple-support-2.7/build/macOS/Python-2.7.13-macosx.x86_64/./python.exe
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _getentropy
  Referenced from: /Users/me/dev/Python-Apple-support-2.7/build/macOS/Python-2.7.13-macosx.x86_64/./python.exe
  Expected in: /usr/lib/libSystem.B.dylib

I'm not really familiar with the python build process, but odd that it's referencing python.exe which would seem to be a windows artifact.  Also odd that it is building macOS even though I had explicitly done a 'make Python.framework-iOS' (but maybe macOS is required for emulator build).

**Comment by freakboy3742** [comment]
This bug was introduced in a recent version of Python (2.7.13?) as part of an across-the-board set of improvements to the entropy sources used for random numbers. I've accounted for this problem in the most recent binary builds (2.7-b3, 3.4-b4, 3.5-b5, 3.6-b2).

If you're still having problems, please open a new ticket with the specifics of the version you're using.

As a side note; the `python.exe` name is a red herring. The python build uses that name as the executable build target, regardless of the platform you're building on. It renames the executable when `make install` is executed.
