### ISSUE TITLE
Implicit declaration of function 'Py_DecodeLocale' is invalid in C99

### ISSUE THREAD

**Issue by Loyv99** [pybee/Python-Apple-support#51]

**Comment by freakboy3742** [comment]
It's very difficult to do anything with this report. You have provided one line of context - presumably the last line of an error log that you have received. We know nothing about what you have done, what you were trying to do, what you expected to see... 

If I was to *guess*, you're using the wrong Python-iOS-template for the version of Python-Apple-support that you've downloaded. However, you've given us nothing to help clarify, so that is entirely a guess.

We're happy to help you; but we need you to help us help you.
